kestra:
  server:
    basic-auth:
      enabled: false
    preview:
      enabled: true
  repository:
    type: h2
  storage:
    type: local
    local:
      basePath: /app/data/storage
  queue:
    type: h2
  tutorial-flows:
    enabled: false
  secret:
    type: env

micronaut:
  security:
    enabled: false
